### ISSUE TITLE
在有联想候选词状态下输入"。"会变成"~~。"，按shift执行`commit_code`指令也会额外输入"~~"

### ISSUE THREAD

**Issue by zhuangzhemin** [shewer/librime-lua-script#10]
在有联想候选词状态下输入"。"会变成"~~。"，按shift执行`commit_code`指令也会额外输入"~~"。需要多按一下ESC退出联想状态。
请问这个有办法优化吗？谢谢！

**Comment by shewer** [comment]
在輸入 符號時 會連同 ~~ 上屏 下次整理 聯想輸入時再改善看看 

context.input : ~~ 是觸發 聯想字典的機制  commit_code 
 中斷 聯想 機制是輸入新的字根鍵 和ESC   ( clear context.input & update context.input)
我想不到適用的方法自動中斷聯想輸入 
你可以keybind 你喜歡的 鍵 去 clear input 
試試下面

key_binder: 下設bindings: 
key_binder/bindings:
     - {when: always, accept: "0" , send: Clear}

**Comment by zhuangzhemin** [comment]
> 在輸入 符號時 會連同 ~~ 上屏 下次整理 聯想輸入時再改善看看
> 
> context.input : ~~ 是觸發 聯想字典的機制 commit_code 中斷 聯想 機制是輸入新的字根鍵 和ESC ( clear context.input & update context.input) 我想不到適用的方法自動中斷聯想輸入 你可以keybind 你喜歡的 鍵 去 clear input 試試下面
> 
> key_binder: 下設bindings: key_binder/bindings: - {when: always, accept: "0" , send: Clear}

感谢答复。我也试着看下这段lua代码学习一下。目前还是先用ESC退出好了，跟VIM保持一致。:-)

**Comment by zhuangzhemin** [comment]
我在这里做了一点修改，暂时把这个shift键切换中英文状态的问题绕过去了。
修改前:
```lua
local escape_key = ".-"
```
修改后:
```lua
local escape_key = ""
```

修改前:
```lua
  if  context.input:match("^" .. pattern_str) then
    -- pass ~<>HBC  select_commit char and  escape_key
    if ascii:match(env.escape_regex) then
      --pass
    elseif ascii:match(env.alphabet_regex) or  ascii:match("^%p$") then
      context:clear()
    --
    elseif key:repr() == "Return" or key:repr() == "BackSpace" then
      context:clear()
      return Accepted
    -- elseif ascii:match(env.escape_regex) then
    else
```
修改后:
```lua
  if  context.input:match("^" .. pattern_str) then
    -- pass ~<>HBC  select_commit char and  escape_key
    if ascii:match(env.escape_regex) then
      --pass
    elseif ascii:match(env.alphabet_regex) or ascii:match("^%p$") then
      context:clear()
    elseif key:repr() == "Return" then
      context:clear()
    elseif key:repr() == "Shift+Shift_L" or key:repr() == "Shift+Shift_R" then
      context:clear()
    elseif key:repr() == "BackSpace" then
      context:clear()
      return Accepted
    end
  end
```

**Comment by shewer** [comment]
> 我在这里做了一点修改，暂时把这个shift键切换中英文状态的问题绕过去了。 修改前:
> 
> ```lua
> local escape_key = ".-"   <----- 這是我的二 三 候選字 上屏快鍵 用key_binder 綁定 send: 2 and 3 應該設在 yaml  name_space 讓user 設定 跳脫字元 預設: 空字串
跳脫字元是爲了上屏聯想候選字   : 1-9  空白 使用者上屏快鍵 
其於字元則 中斷聯想 

> ```
> 

> 修改后:
> 
> ```lua
>   if  context.input:match("^" .. pattern_str) then
>     -- pass ~<>HBC  select_commit char and  escape_key
>     if ascii:match(env.escape_regex) then
>       --pass
>     elseif ascii:match(env.alphabet_regex) or ascii:match("^%p$") then
>       context:clear()
>     elseif key:repr() == "Return" then
>       context:clear()
>     elseif key:repr() == "Shift+Shift_L" or key:repr() == "Shift+Shift_R" then
        我把keyevent   輸出到 log 沒有 "Shift+Shift_L" 
           ```lua
                 puts(DEBUG,__LINE__(), "keyevent"  key:repr(),key.keycode)
           ```
        trace   : 278: keyevent: : Shift_L: 65505
         trace   : 278: keyevent: : Shift+Release+Shift_L: 65505
          trace   : 278: keyevent: : Shift_R: 65506
         trace   : 278: keyevent: : Shift+Release+Shift_R: 65506
>       context:clear()
>     elseif key:repr() == "BackSpace" and #context.input  <3  then <---- 進入 ~~[HBC] or ~~[<>~]  時刪除 input用
 >       context:clear()
>       return Accepted
>     end
>   end
> ```

**Comment by zhuangzhemin** [comment]
> ```
>     我把keyevent   輸出到 log 沒有 "Shift+Shift_L" 
>        ```lua
>              puts(DEBUG,__LINE__(), "keyevent"  key:repr(),key.keycode)
>        ```
>     trace   : 278: keyevent: : Shift_L: 65505
>      trace   : 278: keyevent: : Shift+Release+Shift_L: 65505
>       trace   : 278: keyevent: : Shift_R: 65506
>      trace   : 278: keyevent: : Shift+Release+Shift_R: 65506
> ```

那是windows和linux/mac看到的key:repr()还有差别？我这边打印出来的log信息是'Shift+Shift_L'和'Shift+Shift_R'。
```log
E0325 14:39:33.148155 41576 types.cc:1172] error	: key:repr(): 'Release+space'
E0325 14:39:35.322916 41576 types.cc:1172] error	: key:repr(): 'Shift+Shift_L'
E0325 14:39:38.843353 41576 types.cc:1172] error	: key:repr(): 'Release+space'
E0325 14:39:39.828756 41576 types.cc:1172] error	: key:repr(): 'Shift+Shift_R'
E0325 14:39:42.989121 41576 types.cc:1172] error	: key:repr(): 'Release+space'
E0325 14:39:43.237864 41576 types.cc:1172] error	: key:repr(): 'Control+Control_L'
E0325 14:39:43.396683 41576 types.cc:1172] error	: key:repr(): 'Release+Control_L'
E0325 14:39:43.873997 41576 types.cc:1172] error	: key:repr(): 'f'
E0325 14:39:44.004302 41576 types.cc:1172] error	: key:repr(): 'Release+f'
```

**Comment by shewer** [comment]
哇 這樣子頭大了  可能是librime 版本或是系統
用key:repr()字串比較 ， 不可靠了

可能要用   key:eq(  KeyEvent("Shift_L) )  或是

static const luaL_Reg vars_get[] = {
    { "keycode", WRAP(keycode) },
    { "modifier", WRAP(modifier) },

**Comment by zhuangzhemin** [comment]
这个我就不懂了。我没找到Rime API的文档。只能在大佬的代码上根据我的需求和理解小修小改。

**Comment by zhuangzhemin** [comment]
顺便请教下，哪里有rime api的文档吗？有没有可能直接调用rime已经build好的dict文件？如果可以的话lua script就不用单独准备词库，只要维护一套大词库就可以。

**Comment by shewer** [comment]
只有看 types.cc  librime-lua types.cc   和librime src 配着看
詞庫就讓 table stript    translator 做吧

MemoryReg 可以調用 字典 
lua的 hash table  方便 但 rime的字典是 marisa trie 結構 
一般打字根  是字碼 短到長 直接調用 memory 較快
英文字典是以字元排序不同於  trie  所以才用lua做table 爲了搜尋速度還拆前三碼做索引
aaa
aaaa
aaaaaaa
abaaaaa
ac
