### ISSUE TITLE
输入某些单词的时候会导致软件闪退

### ISSUE THREAD

**Issue by zhuangzhemin** [shewer/librime-lua-script#11]
我用中英混合或者英打模式，在outlook和chrome输入“terminal”时会闪退，能稳定复现。方便的话还请帮忙看看。谢谢！

Rime log信息如下:
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0322 10:06:27.247216 14236 lua_gears.cc:15] LuaTranslation::Next error(2): D:\Home\Rime\lua\tools/english_dict.lua:96: attempt to index a nil value (local 'pw')
E0322 10:07:45.850255 20024 lua_gears.cc:15] LuaTranslation::Next error(2): D:\Home\Rime\lua\tools/english_dict.lua:96: attempt to index a nil value (local 'pw')
E0322 10:08:50.267475 20024 lua_gears.cc:15] LuaTranslation::Next error(2): D:\Home\Rime\lua\tools/english_dict.lua:96: attempt to index a nil value (local 'pw')
E0322 10:09:18.664028 20024 lua_gears.cc:15] LuaTranslation::Next error(2): D:\Home\Rime\lua\tools/english_dict.lua:96: attempt to index a nil value (local 'pw')

**Comment by shewer** [comment]
那是win版 rime 對於 長字串 送上候選選單時會造成崩潰的問題  和librime 沒關係
你試過  改成 "\r" 斷行版本嗎?  如果還是
pw == nil  暫時不影響 還沒修正 

處理方式 1 把english.txt  翻譯字串縮短 , 1用 "#" remake 該單字

**Comment by zhuangzhemin** [comment]
> 那是win版 rime 對於 長字串 送上候選選單時會造成崩潰的問題 和librime 沒關係 你試過 改成 "\r" 斷行版本嗎? 如果還是 pw == nil 暫時不影響 還沒修正
> 
> 處理方式 1 把english.txt 翻譯字串縮短 , 1用 "#" remake 該單字

感谢答复。我按照你描述的问题原因，添加了一个truncate_comment函数来截短comment长度，看上去是可以工作的。谢谢！
```lua
local function truncate_comment(comment)
  local MAX_LENGTH = 80
  local gsub_fmt = package.config:sub(1,1) == "/" and "\n" or "\r"
  local result = comment:gsub("\\n",gsub_fmt)
  if #result > MAX_LENGTH then
    result = result:sub(1, MAX_LENGTH)
  end
  return result
end
```
```lua
  -- 使用 context.input 杳字典 type "english"
  for w in T._eng_dict:iter(inp:sub(seg.start,seg._end)) do
    -- 如果 與 字典相同 替換 first cand.comment
    if first.type == English and input == w.word or input:lower() == w.word then
      first.comment= truncate_comment(w.info)
    else
      yield( Candidate(English,seg.start,seg._end,w.word,truncate_comment(w.info)) )
    end
  end
  -- 使用 ninja 最後一佪字查字典 type "ninja"
  if #commit > 1 then
    --local n_word= commit[#commit]
    local n_word= commit:match(".* (.+)$")

    for w in T._eng_dict:iter(n_word) do
      -- seg.start =   seg.end - #m_word
      yield( Candidate(Ninja, seg._end - #n_word , seg._end,w.word,"(Ninja) " .. truncate_comment(w.info)))
    end
  end
end
```

**Comment by shewer** [comment]
感謝  解決這個問題
直接把utf8字串 切80 可能會有亂碼 , 
我的模組已 require 'tools/string.
所以可以用   result = result:utf8_sub(1, MAX_LENGTH)   
80是 win 版本的上限嗎 ??

**Comment by zhuangzhemin** [comment]
> 感謝 解決這個問題 直接把utf8字串 切80 可能會有亂碼 , 我的模組已 require 'tools/string. 所以可以用 result = result:utf8_sub(1, MAX_LENGTH) 80是 win 版本的上限嗎 ??

80是一般txt文档编码换行的习惯，我个人感觉这么多就能大概知道这个单词是什么含义了。我没试过windows的上限在哪里。后面找时间试试看。

另外我刚试了，用utf8_sub的话就会闪退。我又换回sub了，最后一位乱码就乱码吧。谢谢！

**Comment by zhuangzhemin** [comment]
> > 感謝 解決這個問題 直接把utf8字串 切80 可能會有亂碼 , 我的模組已 require 'tools/string. 所以可以用 result = result:utf8_sub(1, MAX_LENGTH) 80是 win 版本的上限嗎 ??
> 
> 80是一般txt文档编码换行的习惯，我个人感觉这么多就能大概知道这个单词是什么含义了。我没试过windows的上限在哪里。后面找时间试试看。
> 
> 另外我刚试了，用utf8_sub的话就会闪退。我又换回sub了，最后一位乱码就乱码吧。谢谢！

又试了一下，用utf8_sub是可以的，而且最后一位也不会乱码。但是要注意MAX_LENGTH的长度。我试下来，MAX_LENGTH最大只能到58。如果是59以上，软件就会闪退。这个看上去跟输入单词的长度没关系，用“cle”和”commercialism“测试下来都是58可以59不行。不知道有没有其它因素会影响这个最大长度，保守一点，我先用MAX_LENGTH=50吧。
```lua
local function truncate_comment(comment)
  local MAX_LENGTH = 50
  local gsub_fmt = package.config:sub(1,1) == "/" and "\n" or "\r"
  local result = comment:gsub("\\n",gsub_fmt)
  if #result > MAX_LENGTH then
    result = result:utf8_sub(1, MAX_LENGTH)
  end
  return result
end
```

**Comment by zhuangzhemin** [comment]
> Rime log信息如下: Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg E0322 10:06:27.247216 14236 lua_gears.cc:15] LuaTranslation::Next error(2): D:\Home\Rime\lua\tools/english_dict.lua:96: attempt to index a nil value (local 'pw') E0322 10:07:45.850255 20024 lua_gears.cc:15] LuaTranslation::Next error(2): D:\Home\Rime\lua\tools/english_dict.lua:96: attempt to index a nil value (local 'pw') E0322 10:08:50.267475 20024 lua_gears.cc:15] LuaTranslation::Next error(2): D:\Home\Rime\lua\tools/english_dict.lua:96: attempt to index a nil value (local 'pw') E0322 10:09:18.664028 20024 lua_gears.cc:15] LuaTranslation::Next error(2): D:\Home\Rime\lua\tools/english_dict.lua:96: attempt to index a nil value (local 'pw')

english_dict.lua文件第96行这个报错信息，可以通过如下修改第85行代码来避免。
修改前:
```lua
local pw= w:match("^[%a][%a%.%-_]*")
```
修改后:
```lua
local pw= w:match("^[%a][%a%.%-_]*") or ""
````


另外还有294行也经常报错，可以通过如下修改解决。
修改前:
```lua
function English:find_index(org_text)
  local key= ( org_text:match("^([%a%.%_%-]+).*") or "")
  :lower()
  :sub(1, self._level )
```
修改后:
```lua
function English:find_index(org_text)
  local key=  org_text and org_text:match("^([%a%.%_%-]+).*") or ""
  key = key:lower():sub(1, self._level )
```
