### ISSUE TITLE
聯想功能在trime (for Android)中運作異常

### ISSUE THREAD

**Issue by spew8712** [shewer/librime-lua-script#16]
測試在預設的cangjie5方案中加載此腳本
結果會在按下按鍵，commit前之候選階段就顯示聯想項（排在原本候選項後面），嚴重拖累性能
不知這是否就是「README>聯想詞彙>增加候選字聯想: 暫時不適用( 拼音類輸入法 候選字太多 )」所謂不適用的行為？
是不是可能跟trime所採用之librime-lua版本 (https://github.com/hchunhui/librime-lua/tree/fff26227fc126b2e266454f932e69936ec6664d7) 較舊有關呢？
還是腳本中有什麼能直接改善的作法？

**Comment by shewer** [comment]
理論上，不應該  只要 menu/page_size 滿了 就會暫停，可以給我輸入那些字時會發生
還有聯想字典在init 時已排序了，每單字庫最大也只有2xxxx 筆詞
(一: 是最多的詞你可以試試) 


建議在linux  or win  下測試完在放到trime中
基本上我在trime上用沒有問題


如果不要預先聯想 可以先將 conjunctive/filter.lua 中的插入聯想上屏迴圈 remark掉
形碼輸入a候選字少可預先候選，( 這塊 remark 掉可以停掉 預聯想
https://github.com/shewer/librime-lua-script/blob/08d27ec5d224f5ddd992119303e4f93806ae9034/lua/conjunctive/filter.lua#L57-L69
拼音同音字太多，造成排不上第一頁，而失去預聯想的機制，有兩個條件可介入預選 
  1. 成詞時 (utf8.len(cand.text) >1 
  2. count 設定上屏N個後  中斷 ，改聯想上屏 ，

**Comment by spew8712** [comment]
註解掉那塊之後，問題就解決了，trime上的行爲總算跟weasel一致。
額外測試了在windows也註解掉，沒看到變化。這代表weasel有沒有那塊其實沒差（？
