### ISSUE TITLE
英文模式首字母大写，候选字不会自动变成首字母大写模式

### ISSUE THREAD

**Issue by zhuangzhemin** [shewer/librime-lua-script#5]
我这边测试下来的情况如下:
![image](https://user-images.githubusercontent.com/20674069/158921325-41e94d45-8813-4268-b808-0ba1e8bbc3dc.png)

您这边另外一个rime-english repo[https://github.com/shewer/rime-english]有提到可以
```
支持大小寫混合輸入，候選單詞自動匹配。輸入模式儘量符合 英打模式
```
请问是这个版本没有支持这个功能，还是我配置哪里有问题吗？谢谢！

**Comment by shewer** [comment]
應該和配置無關
我己重新改寫 加上 ninja 功能 , 查找字典是通配的 在candidate是會列出，
英打模式 我是不想 字典干擾 使用者輸入字串 只是沒把 comment 訊息 和第一個candidate 同步

**Comment by zhuangzhemin** [comment]
> 應該和配置無關 我己重新改寫 加上 ninja 功能 , 查找字典是通配的 在candidate是會列出， 英打模式 我是不想 字典干擾 使用者輸入字串 只是沒把 comment 訊息 和第一個candidate 同步

感谢答复。我也试着看下这段lua代码学习一下。

**Comment by shewer** [comment]
已經改好了 你可以幫忙測試 window 版本 嗎
1 英打模式   會自動切換 ascii_punct on  回中文模式 還原user 模式
2 input  和單字比較 增加  input:lower() == w.word   同步 cand.comment
3 comment 增加斷行處理 ( linux OK  window ??)
4 process_plugin  增加 english/tag: abc (中英混打) & english/dictionary: english (簡體翻譯)

**Comment by zhuangzhemin** [comment]
> 已經改好了 你可以幫忙測試 window 版本 嗎 1 英打模式 會自動切換 ascii_punct on 回中文模式 還原user 模式 2 input 和單字比較 增加 input:lower() == w.word 同步 cand.comment 3 comment 增加斷行處理 ( linux OK window ??) 4 process_plugin 增加 english/tag: abc (中英混打) & english/dictionary: english (簡體翻譯)

这个跟我原始表达的需求还不一样。我试着改了一段代码:
```lua
local function sync_case(input, candidate_word)
  local is_first_char_cap = input:sub(1,1):upper() == input:sub(1,1)
  local is_second_char_cap = input:sub(2,2):upper() == input:sub(2,2)
  if is_first_char_cap and is_second_char_cap then
    return candidate_word:upper()
  elseif is_first_char_cap then
    return candidate_word:sub(1,1):upper() .. candidate_word:sub(2)
  else
    return candidate_word
  end
end
```
```lua
  -- 使用 context.input 杳字典 type "english"
  for w in T._eng_dict:iter(inp:sub(seg.start,seg._end)) do
    -- 如果 與 字典相同 替換 first cand.comment
    if first.type == English and input:lower() == w.word then
      first.comment= truncate_comment(w.info)
    else
      yield( Candidate(English,seg.start,seg._end,sync_case(input,w.word),truncate_comment(w.info)) )
    end
  end
```
修改后使用效果如下。根据input的第1-2位的大小写状态，自动同步候选字为默认、首字母大写或者全大写。
![image](https://user-images.githubusercontent.com/20674069/159688172-3513e5f1-930b-4985-92d2-63bbd6f83e45.png)

**Comment by zhuangzhemin** [comment]
这样改完，不能用数字键选择候选词了。还要再看下代码。shewer大佬有什么建议吗？谢谢！

**Comment by shewer** [comment]
:不是很了解 code 目的， 大寫只有在英打模式才可用，中打模式 正常只有小寫字根
可是應該不影響 數字選字才對
除非有 lua_processor 把數字收下 

我用你的function在英打模式下 測試 是OK可行的 
 我的中文模式 不接受大寫字元 不測試     
Ther4 Therapeutically
THer4 THERAPEUTICALLY

發現一個狀態被 patterns url  攔下 
input:  a.a8  包含 "."   時輸入數字時結果  recognizer 攔下打上url tag     a.a8
 
url pattern: 
c:recognizer/patterns/url--(^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$)
^[a-z]+[.].+ 

解決方法   在english_proc 加入 selector 機制  2. 移除 url  or  ^[a-z]+[.].+$ 字段

**Comment by shewer** [comment]
https://github.com/shewer/librime-lua-script/blob/dev/lua/component/debug_filter.lua
可以用 component/debug_filter.lua 
set_option("_debug",true)  打開 顯示 , 
也可以用 command module  /o:_debug:true{Space}  

```
a.m <---------------------
schema: whaleliu_ext / 【鯨舞倉】詞
status: composing
[a.m]|(english) [tags: english]
page: 1  (of size 9)
1. [a.m][english]|--Simple|english|0|3||0.0|
2.  a m [ninja]|--Simple|ninja|0|3||0.0|
3.  a.m. 上午, 午前|--Simple|english|0|3||0.0|
4.  M (Ninja)  [計] 尾數, 主要, 媒體, 介質, 中等, 存儲器, 方式, 分, 模, 乘法器, 兆, 毫
 [醫] 容積克分子(溶液), 容模的|--Simple|ninja|2|3||0.0|
5.  MA (Ninja)  n. 媽
 [計] 存儲器地址, 多路存取|--Simple|ninja|2|3||0.0|
6.  ma'am (Ninja)  n. 夫人, 女王, 公主|--Simple|ninja|2|3||0.0|
7.  Maastricht (Ninja)  n. 馬斯特裡赫特（荷蘭東南部城市）|--Simple|ninja|2|3||0.0|
8.  MAB (Ninja)  [計] 內存分配塊|--Simple|ninja|2|3||0.0|
9.  mabel (Ninja)  n. 梅布爾（女子名）|--Simple|ninja|2|3||0.0|
3

schema: whaleliu_ext / 【鯨舞倉】詞
status: composing
[a.m3]| [tags: url]  <-------------  3 被 patterns: url 截下 push to input   井打上 url tag

```

**Comment by zhuangzhemin** [comment]
> :不是很了解 code 目的， 大寫只有在英打模式才可用，中打模式 正常只有小寫字根 可是應該不影響 數字選字才對 除非有 lua_processor 把數字收下
> 
> 我用你的function在英打模式下 測試 是OK可行的 我的中文模式 不接受大寫字元 不測試 Ther4 Therapeutically THer4 THERAPEUTICALLY
> 
> 發現一個狀態被 patterns url 攔下 input: a.a8 包含 "." 時輸入數字時結果 recognizer 攔下打上url tag a.a8
> 
> url pattern: c:recognizer/patterns/url--(^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$) ^[a-z]+[.].+
> 
> 解決方法 在english_proc 加入 selector 機制 2. 移除 url or ^[a-z]+[.].+$ 字段

感谢答复。我找到原因了。是因为我在*.scheme.yaml里面的recognizer添加了`import_preset: default`，这个会导入默认的`uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"`的pattern，首字母大写的input就被认为是uppercase，rime的后续处理机制就不一样了。我把这句`import_preset: default`注释掉，现在首字母大写也可以用数字键选字了。谢谢！
```lua
recognizer:
  # import_preset: default
  patterns:
    reverse_lookup: "[a-z`]*`+[a-z`]*"
```
