### ISSUE TITLE
切换到英文输入后，有办法把“，”、"。"符号输入自动改成","、"."吗？

### ISSUE THREAD

**Issue by zhuangzhemin** [shewer/librime-lua-script#6]
如题，现在用英文输入整个句子之后，输入“."得到的是中文状态的"。"。谢谢！

**Comment by zhuangzhemin** [comment]
我在lua/english/init.lua文件的
```lua
function S.func(segs ,env) -- segmetation:Segmentation,env_
  local context=env.engine.context
  local cartpos= segs:get_current_start_position()
```
之后添加了这段，现在可以自动切换了。非常感谢！
```lua
  local ASCII_PUNCT="ascii_punct"
  if context:get_option(English) then
    context:set_option(ASCII_PUNCT, true)
  else
    context:set_option(ASCII_PUNCT, false)
  end
```

**Comment by shewer** [comment]
在 P.init(env) 加上 option_update_notifier
 保存user 狀態 English  off 時還原
```lua
context.option_update_notifier:connect(function(ctx,name)
  if name == English then
    if ctx:get_option(name) then
      env.save_ascii_punct= ctx:get_option(ASCII_PUNCT)
      ctx:set_option(ASCII_PUNCT,true)
    else
      ctx:set_option(ASCII_PUNCT,env.save_ascii_punct) --<<<<   opttion 多個t
    end
  end
end)
```

**Comment by zhuangzhemin** [comment]
> 在 P.init(env) 加上 option_update_notifier 保存user 狀態 English off 時還原
> 
> ```lua
> context.option_update_notifier:connect(function(ctx,name)
>   if name == English then
>     if ctx:get_option(name) then
>       env.save_ascii_punct= ctx:get_option(ASCII_PUNCT)
>       ctx:set_option(ASCII_PUNCT,true)
>     else
>       ctx:set_opttion(ASCII_PUNCT,env.save_ascii_punct)
>     end
>   end
> end)
> ```

这个改动好像有点问题。切换到英打模式后会开启ASCII_PUNCT，但是切换回中英文混合输入模式后不会自动变回ASCII_PUNCT false状态。不过这段代码本身我看不出有什么问题。不知道是不是这样切换的时候这段代码实际上会被调用不止一遍，导致env.save_ascii_punct保存的是前一遍true的状态。谢谢！

**Comment by shewer** [comment]
ctx:set_opttion()    多個 t    , 改正了

**Comment by zhuangzhemin** [comment]
> ctx:set_opttion() 多個 t , 改正了

可以用了，感谢

**Comment by shewer** [comment]
英文comment 有斷行嗎??
