### ISSUE TITLE
有可能实现中英文混合输入吗？谢谢！

### ISSUE THREAD

**Issue by zhuangzhemin** [shewer/librime-lua-script#7]
有时会需要使用一些中英文混合的句子，比如”这个输入法在windows下也可以使用“。有可能做成不需要中/英文来回切换的吗？谢谢！

**Comment by shewer** [comment]
方案中加上 patch，把english/tag: abc  或是 abc_segment: [english]

就可以觸發英文字典 只是 不像英打模式順暢  ，英打模式  空白 , . 會直接上屏 ，中英模式
需要空白鍵是上屏鍵 ，要間隔就得要再補上空白
```
patch:
   english/tag: abc
```

**Comment by zhuangzhemin** [comment]
> 方案中加上 patch，把english/tag: abc 或是 abc_segment: [english]
> 
> 就可以觸發英文字典 只是 不像英打模式順暢 ，英打模式 空白 , . 會直接上屏 ，中英模式 需要空白鍵是上屏鍵 ，要間隔就得要再補上空白
> 
> ```
> patch:
>    english/tag: abc
> ```

感谢耐心答复。这个我刚试了，跟我想要的还不是同一个事情。加上这个选项之后，英打模式还是只能匹配到英文。
我想请教的是，有没有可能我打“keyizai”得到“可以在”，然后不需要切换到英打模式，直接在中文模式继续输入“windows"，也能匹配到对应的英文单词呢？这样输入“可以在windows使用”之类的中英混合句子，就可以不用来回切换模式了。谢谢！

**Comment by zhuangzhemin** [comment]
> 方案中加上 patch，把english/tag: abc 或是 abc_segment: [english]
> 
> 就可以觸發英文字典 只是 不像英打模式順暢 ，英打模式 空白 , . 會直接上屏 ，中英模式 需要空白鍵是上屏鍵 ，要間隔就得要再補上空白
> 
> ```
> patch:
>    english/tag: abc
> ```

感谢耐心答复，这个选项开启后，完美实现了在中文模式下混合输入中英文的需求。
